# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: x.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='x.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x07x.proto\"1\n\x14RegisterCommunicator\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03pid\x18\x02 \x01(\t\"\x9c\x01\n\x1aTrafficGeneratorParameters\x12\x1b\n\x13\x64istribution_period\x18\x01 \x01(\t\x12\x19\n\x11parameters_period\x18\x02 \x03(\x02\x12#\n\x1b\x64istribution_execution_time\x18\x03 \x01(\t\x12!\n\x19parameters_execution_time\x18\x04 \x03(\x02\"!\n\x0eMessageRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"a\n\x0eSimulationInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x19\n\x11simulation_length\x18\x02 \x01(\x05\x12\x13\n\x0btick_length\x18\x03 \x01(\x02\x12\x11\n\tipaddress\x18\x04 \x01(\t\"4\n\x07\x43ounter\x12\x1a\n\x12\x61\x63tor_type_counter\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02\"&\n\x08\x43ounters\x12\x1a\n\x08\x63ounters\x18\x01 \x03(\x0b\x32\x08.Counter\"\xf6\x01\n\x0fToPythonMessage\x12\x13\n\x0btransfer_id\x18\x01 \x01(\x05\x12\x13\n\x0btick_offset\x18\x02 \x01(\x05\x12\x12\n\npid_sender\x18\x03 \x01(\t\x12\"\n\x07request\x18\x04 \x01(\x0b\x32\x0f.MessageRequestH\x00\x12\x1f\n\x04info\x18\x05 \x01(\x0b\x32\x0f.SimulationInfoH\x00\x12\x36\n\x15register_communicator\x18\x06 \x01(\x0b\x32\x15.RegisterCommunicatorH\x00\x12\x1d\n\x08\x63ounters\x18\x07 \x01(\x0b\x32\t.CountersH\x00\x42\t\n\x07payload\"\x8c\x01\n\x13ToSimulationMessage\x12\x13\n\x0btransfer_id\x18\x01 \x01(\x05\x12\x14\n\x0cpid_receiver\x18\x02 \x01(\t\x12?\n\x18traffic_generator_params\x18\x03 \x01(\x0b\x32\x1b.TrafficGeneratorParametersH\x00\x42\t\n\x07payload\"<\n\x12ResponseSimulation\x12&\n\x08messages\x18\x01 \x03(\x0b\x32\x14.ToSimulationMessageb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_REGISTERCOMMUNICATOR = _descriptor.Descriptor(
  name='RegisterCommunicator',
  full_name='RegisterCommunicator',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='RegisterCommunicator.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pid', full_name='RegisterCommunicator.pid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=11,
  serialized_end=60,
)


_TRAFFICGENERATORPARAMETERS = _descriptor.Descriptor(
  name='TrafficGeneratorParameters',
  full_name='TrafficGeneratorParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='distribution_period', full_name='TrafficGeneratorParameters.distribution_period', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parameters_period', full_name='TrafficGeneratorParameters.parameters_period', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='distribution_execution_time', full_name='TrafficGeneratorParameters.distribution_execution_time', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parameters_execution_time', full_name='TrafficGeneratorParameters.parameters_execution_time', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=219,
)


_MESSAGEREQUEST = _descriptor.Descriptor(
  name='MessageRequest',
  full_name='MessageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='MessageRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=254,
)


_SIMULATIONINFO = _descriptor.Descriptor(
  name='SimulationInfo',
  full_name='SimulationInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='SimulationInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='simulation_length', full_name='SimulationInfo.simulation_length', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tick_length', full_name='SimulationInfo.tick_length', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ipaddress', full_name='SimulationInfo.ipaddress', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=353,
)


_COUNTER = _descriptor.Descriptor(
  name='Counter',
  full_name='Counter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='actor_type_counter', full_name='Counter.actor_type_counter', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='Counter.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=355,
  serialized_end=407,
)


_COUNTERS = _descriptor.Descriptor(
  name='Counters',
  full_name='Counters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='counters', full_name='Counters.counters', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=409,
  serialized_end=447,
)


_TOPYTHONMESSAGE = _descriptor.Descriptor(
  name='ToPythonMessage',
  full_name='ToPythonMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='transfer_id', full_name='ToPythonMessage.transfer_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tick_offset', full_name='ToPythonMessage.tick_offset', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pid_sender', full_name='ToPythonMessage.pid_sender', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='request', full_name='ToPythonMessage.request', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='info', full_name='ToPythonMessage.info', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='register_communicator', full_name='ToPythonMessage.register_communicator', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='counters', full_name='ToPythonMessage.counters', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='ToPythonMessage.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=450,
  serialized_end=696,
)


_TOSIMULATIONMESSAGE = _descriptor.Descriptor(
  name='ToSimulationMessage',
  full_name='ToSimulationMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='transfer_id', full_name='ToSimulationMessage.transfer_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pid_receiver', full_name='ToSimulationMessage.pid_receiver', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='traffic_generator_params', full_name='ToSimulationMessage.traffic_generator_params', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='ToSimulationMessage.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=699,
  serialized_end=839,
)


_RESPONSESIMULATION = _descriptor.Descriptor(
  name='ResponseSimulation',
  full_name='ResponseSimulation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messages', full_name='ResponseSimulation.messages', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=841,
  serialized_end=901,
)

_COUNTERS.fields_by_name['counters'].message_type = _COUNTER
_TOPYTHONMESSAGE.fields_by_name['request'].message_type = _MESSAGEREQUEST
_TOPYTHONMESSAGE.fields_by_name['info'].message_type = _SIMULATIONINFO
_TOPYTHONMESSAGE.fields_by_name['register_communicator'].message_type = _REGISTERCOMMUNICATOR
_TOPYTHONMESSAGE.fields_by_name['counters'].message_type = _COUNTERS
_TOPYTHONMESSAGE.oneofs_by_name['payload'].fields.append(
  _TOPYTHONMESSAGE.fields_by_name['request'])
_TOPYTHONMESSAGE.fields_by_name['request'].containing_oneof = _TOPYTHONMESSAGE.oneofs_by_name['payload']
_TOPYTHONMESSAGE.oneofs_by_name['payload'].fields.append(
  _TOPYTHONMESSAGE.fields_by_name['info'])
_TOPYTHONMESSAGE.fields_by_name['info'].containing_oneof = _TOPYTHONMESSAGE.oneofs_by_name['payload']
_TOPYTHONMESSAGE.oneofs_by_name['payload'].fields.append(
  _TOPYTHONMESSAGE.fields_by_name['register_communicator'])
_TOPYTHONMESSAGE.fields_by_name['register_communicator'].containing_oneof = _TOPYTHONMESSAGE.oneofs_by_name['payload']
_TOPYTHONMESSAGE.oneofs_by_name['payload'].fields.append(
  _TOPYTHONMESSAGE.fields_by_name['counters'])
_TOPYTHONMESSAGE.fields_by_name['counters'].containing_oneof = _TOPYTHONMESSAGE.oneofs_by_name['payload']
_TOSIMULATIONMESSAGE.fields_by_name['traffic_generator_params'].message_type = _TRAFFICGENERATORPARAMETERS
_TOSIMULATIONMESSAGE.oneofs_by_name['payload'].fields.append(
  _TOSIMULATIONMESSAGE.fields_by_name['traffic_generator_params'])
_TOSIMULATIONMESSAGE.fields_by_name['traffic_generator_params'].containing_oneof = _TOSIMULATIONMESSAGE.oneofs_by_name['payload']
_RESPONSESIMULATION.fields_by_name['messages'].message_type = _TOSIMULATIONMESSAGE
DESCRIPTOR.message_types_by_name['RegisterCommunicator'] = _REGISTERCOMMUNICATOR
DESCRIPTOR.message_types_by_name['TrafficGeneratorParameters'] = _TRAFFICGENERATORPARAMETERS
DESCRIPTOR.message_types_by_name['MessageRequest'] = _MESSAGEREQUEST
DESCRIPTOR.message_types_by_name['SimulationInfo'] = _SIMULATIONINFO
DESCRIPTOR.message_types_by_name['Counter'] = _COUNTER
DESCRIPTOR.message_types_by_name['Counters'] = _COUNTERS
DESCRIPTOR.message_types_by_name['ToPythonMessage'] = _TOPYTHONMESSAGE
DESCRIPTOR.message_types_by_name['ToSimulationMessage'] = _TOSIMULATIONMESSAGE
DESCRIPTOR.message_types_by_name['ResponseSimulation'] = _RESPONSESIMULATION

RegisterCommunicator = _reflection.GeneratedProtocolMessageType('RegisterCommunicator', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERCOMMUNICATOR,
  __module__ = 'x_pb2'
  # @@protoc_insertion_point(class_scope:RegisterCommunicator)
  ))
_sym_db.RegisterMessage(RegisterCommunicator)

TrafficGeneratorParameters = _reflection.GeneratedProtocolMessageType('TrafficGeneratorParameters', (_message.Message,), dict(
  DESCRIPTOR = _TRAFFICGENERATORPARAMETERS,
  __module__ = 'x_pb2'
  # @@protoc_insertion_point(class_scope:TrafficGeneratorParameters)
  ))
_sym_db.RegisterMessage(TrafficGeneratorParameters)

MessageRequest = _reflection.GeneratedProtocolMessageType('MessageRequest', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGEREQUEST,
  __module__ = 'x_pb2'
  # @@protoc_insertion_point(class_scope:MessageRequest)
  ))
_sym_db.RegisterMessage(MessageRequest)

SimulationInfo = _reflection.GeneratedProtocolMessageType('SimulationInfo', (_message.Message,), dict(
  DESCRIPTOR = _SIMULATIONINFO,
  __module__ = 'x_pb2'
  # @@protoc_insertion_point(class_scope:SimulationInfo)
  ))
_sym_db.RegisterMessage(SimulationInfo)

Counter = _reflection.GeneratedProtocolMessageType('Counter', (_message.Message,), dict(
  DESCRIPTOR = _COUNTER,
  __module__ = 'x_pb2'
  # @@protoc_insertion_point(class_scope:Counter)
  ))
_sym_db.RegisterMessage(Counter)

Counters = _reflection.GeneratedProtocolMessageType('Counters', (_message.Message,), dict(
  DESCRIPTOR = _COUNTERS,
  __module__ = 'x_pb2'
  # @@protoc_insertion_point(class_scope:Counters)
  ))
_sym_db.RegisterMessage(Counters)

ToPythonMessage = _reflection.GeneratedProtocolMessageType('ToPythonMessage', (_message.Message,), dict(
  DESCRIPTOR = _TOPYTHONMESSAGE,
  __module__ = 'x_pb2'
  # @@protoc_insertion_point(class_scope:ToPythonMessage)
  ))
_sym_db.RegisterMessage(ToPythonMessage)

ToSimulationMessage = _reflection.GeneratedProtocolMessageType('ToSimulationMessage', (_message.Message,), dict(
  DESCRIPTOR = _TOSIMULATIONMESSAGE,
  __module__ = 'x_pb2'
  # @@protoc_insertion_point(class_scope:ToSimulationMessage)
  ))
_sym_db.RegisterMessage(ToSimulationMessage)

ResponseSimulation = _reflection.GeneratedProtocolMessageType('ResponseSimulation', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSESIMULATION,
  __module__ = 'x_pb2'
  # @@protoc_insertion_point(class_scope:ResponseSimulation)
  ))
_sym_db.RegisterMessage(ResponseSimulation)


# @@protoc_insertion_point(module_scope)
